/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Negocio.PacienteControl;
import Presentacion.FrmExpediente;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author chiqu
 */
public class FrmBusqueda extends javax.swing.JInternalFrame {

    private final PacienteControl CONTROL;
    private String accion;
    private String nombresAnt;
    private int idPaciente;
    private String documentoAnt;
    private FrmPacientes frmRegistroPacientes;
    
    public FrmBusqueda() {
        initComponents();
        this.CONTROL = new PacienteControl();
        this.accion = "guardar";
        this.listar("");
    }
    
    public void setFrmRegistroPacientes(FrmPacientes frm){
        this.frmRegistroPacientes = frm;
    }
    
    
    private void mensajeError(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Sistema", JOptionPane.ERROR_MESSAGE);
    }

    private void mensajeOk(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Sistema", JOptionPane.INFORMATION_MESSAGE);
    }
    
    
   private void listar(String texto){

       tablaPacientes.setModel(this.CONTROL.listar(texto));
       TableRowSorter orden = new TableRowSorter(tablaPacientes.getModel());
       tablaPacientes.setRowSorter(orden);
       
       jLabelPacientesRegistrados.setText("Mostrando " + this.CONTROL.totalMostrado() + " de un total de " 
       + this.CONTROL.totalMostrado());
       
       this.accion = "guardar";

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscarExpediente = new javax.swing.JTextField();
        btnBuscarExpediente = new javax.swing.JButton();
        jLabelPacientesRegistrados = new javax.swing.JLabel();
        btnModificarExpediente = new javax.swing.JButton();
        btnActivarExpediente = new javax.swing.JButton();
        btnDesactivarExpediente = new javax.swing.JButton();
        tablaListadoExpediente = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();
        btnVerExpediente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Busqueda de Pacientes");

        btnBuscarExpediente.setText("Buscar:");
        btnBuscarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarExpedienteActionPerformed(evt);
            }
        });

        jLabelPacientesRegistrados.setText("Pacientes registrados:");

        btnModificarExpediente.setText("Modificar");
        btnModificarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarExpedienteActionPerformed(evt);
            }
        });

        btnActivarExpediente.setText("Activar");
        btnActivarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarExpedienteActionPerformed(evt);
            }
        });

        btnDesactivarExpediente.setText("Desactivar");
        btnDesactivarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarExpedienteActionPerformed(evt);
            }
        });

        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaListadoExpediente.setViewportView(tablaPacientes);

        btnVerExpediente.setText("Ver Expediente");
        btnVerExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerExpedienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabelPacientesRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBuscarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVerExpediente)
                        .addGap(28, 28, 28)
                        .addComponent(btnModificarExpediente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActivarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnDesactivarExpediente)
                        .addGap(202, 202, 202))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarExpediente)
                            .addComponent(tablaListadoExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(189, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarExpediente)
                    .addComponent(jLabelPacientesRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(tablaListadoExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerExpediente)
                    .addComponent(btnModificarExpediente)
                    .addComponent(btnActivarExpediente)
                    .addComponent(btnDesactivarExpediente))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarExpedienteActionPerformed
       // 1. Validar selección de la tabla
    if (tablaPacientes.getSelectedRowCount() == 1) {
        int fila = tablaPacientes.getSelectedRow();

        // 2. Extraer todos los datos de la fila (Asegúrate de que los índices 0, 1, 2... coincidan con tus columnas)
        int id = Integer.parseInt(tablaPacientes.getValueAt(fila, 0).toString());
        String nombre = tablaPacientes.getValueAt(fila, 1).toString();
        String apellido = tablaPacientes.getValueAt(fila, 2).toString();
        String documento = tablaPacientes.getValueAt(fila, 3).toString();
        String telefono = tablaPacientes.getValueAt(fila, 4).toString();
        String correo = tablaPacientes.getValueAt(fila, 5).toString();
        String edad = tablaPacientes.getValueAt(fila, 6).toString();
        String direccion = tablaPacientes.getValueAt(fila, 7).toString();
        String historial = tablaPacientes.getValueAt(fila, 8).toString();

        // 3. Instanciar el NUEVO formulario de modificación
        FrmModificarPaciente frmMod = new FrmModificarPaciente();
        
        // 4. Inyectarle los datos extraídos de la tabla
        frmMod.cargarDatos(id, nombre, apellido, documento, telefono, correo, edad, direccion, historial);
        
        // 5. Agregarlo al DesktopPane del MDI principal y mostrarlo en pantalla
        this.getDesktopPane().add(frmMod);
        frmMod.setVisible(true);
        frmMod.toFront();
        
        // 6. Opcional: Cerrar esta ventana de búsqueda para despejar espacio
        this.dispose();
        
    } else {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un único paciente de la tabla para modificar.", "Sistema", JOptionPane.WARNING_MESSAGE);
    }
    
     
        
    }//GEN-LAST:event_btnModificarExpedienteActionPerformed

    private void btnBuscarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarExpedienteActionPerformed
        String textoBusqueda = txtBuscarExpediente.getText().trim();
        listar(textoBusqueda);
    }//GEN-LAST:event_btnBuscarExpedienteActionPerformed

    private void btnActivarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarExpedienteActionPerformed
         if(tablaPacientes.getSelectedRowCount() == 1){
            String id = String.valueOf(tablaPacientes.getValueAt(tablaPacientes.getSelectedRow(), 0));
            String nombre = String.valueOf(tablaPacientes.getValueAt(tablaPacientes.getSelectedRow(), 1));
            if(JOptionPane.showConfirmDialog(this, "Desaea activar el registro: " + nombre + "?", "Activar: ", JOptionPane.YES_NO_OPTION) == 0){
                String resp = this.CONTROL.activar(Integer.parseInt(id));
                if(resp.equals("OK")){
                    this.mensajeOk("Registro Activado");
                    this.listar("");
                }else{
                    this.mensajeError(resp);
                }
            }
        }else{
            this.mensajeError("Seleccion un registro que desea activar");
        }
    
    }//GEN-LAST:event_btnActivarExpedienteActionPerformed

    private void btnDesactivarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarExpedienteActionPerformed
        if(tablaPacientes.getSelectedRowCount() == 1){
             String id = String.valueOf(tablaPacientes.getValueAt(tablaPacientes.getSelectedRow(), 0));
            String nombre = String.valueOf(tablaPacientes.getValueAt(tablaPacientes.getSelectedRow(), 1));
            if(JOptionPane.showConfirmDialog(this, "¿Desea desactivar registro: " + nombre + "?", "Desactivar", JOptionPane.YES_NO_OPTION) == 0){
                String resp = this.CONTROL.desactivar(Integer.parseInt(id));
                if(resp.equals("OK")){
                    this.mensajeOk("Registro desactivado");
                    this.listar("");
                }else{
                    this.mensajeError(resp);
                }
            }
        }else{
            this.mensajeError("Seleccion un registro que desee desactivar");
        }
    
    }//GEN-LAST:event_btnDesactivarExpedienteActionPerformed

    private void btnVerExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerExpedienteActionPerformed
                                               
     if(tablaPacientes.getSelectedRow() ==1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un paciente de la tabla", "Informe", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int fila=tablaPacientes.getSelectedRow();
        int id= Integer.parseInt(tablaPacientes.getValueAt(fila, 0).toString());
        FrmExpediente frm = new FrmExpediente();
        frm.cargarExpediente(id);
        this.getDesktopPane().add(frm);
        frm.setVisible(true);
        frm.toFront();

    }//GEN-LAST:event_btnVerExpedienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivarExpediente;
    private javax.swing.JButton btnBuscarExpediente;
    private javax.swing.JButton btnDesactivarExpediente;
    private javax.swing.JButton btnModificarExpediente;
    private javax.swing.JButton btnVerExpediente;
    private javax.swing.JLabel jLabelPacientesRegistrados;
    private javax.swing.JScrollPane tablaListadoExpediente;
    private javax.swing.JTable tablaPacientes;
    private javax.swing.JTextField txtBuscarExpediente;
    // End of variables declaration//GEN-END:variables
}

