/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author chiqu
 */
public class FrmVistaSemanal extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmVistaSemanal
     */
    public FrmVistaSemanal() {
        initComponents();
        dcFiltroFecha.setDate(new java.util.Date());
    
    // Forzar la primera búsqueda automática
    java.sql.Date hoy = new java.sql.Date(new java.util.Date().getTime());
    datos.CitaDAO datosCita = new datos.CitaDAO();
    tablaCitasGenerales.setModel(datosCita.listarTodasLasCitasPorFecha(hoy));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dcFiltroFecha = new com.toedter.calendar.JDateChooser();
        btnFiltrarFecha = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitasGenerales = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Vista Semanal");

        btnFiltrarFecha.setText("Filtrar fecha");
        btnFiltrarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarFechaActionPerformed(evt);
            }
        });

        tablaCitasGenerales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaCitasGenerales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnFiltrarFecha)
                        .addGap(190, 190, 190)
                        .addComponent(dcFiltroFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFiltrarFecha)
                    .addComponent(dcFiltroFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarFechaActionPerformed
        // 1. Validar que hayan seleccionado una fecha en el calendario
    if (dcFiltroFecha.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha para buscar.", "Sistema", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // 2. Convertir la fecha a formato SQL seguro
        java.util.Date fechaUtil = dcFiltroFecha.getDate();
        java.sql.Date fechaSQL = new java.sql.Date(fechaUtil.getTime());

        // 3. Llamar al DAO y pintar la tabla del centro
        datos.CitaDAO datosCita = new datos.CitaDAO();
        tablaCitasGenerales.setModel(datosCita.listarTodasLasCitasPorFecha(fechaSQL));

        // 4. Avisar si no hay agendas para ese día
        if (tablaCitasGenerales.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay citas programadas para la fecha seleccionada.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al filtrar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnFiltrarFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrarFecha;
    private com.toedter.calendar.JDateChooser dcFiltroFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCitasGenerales;
    // End of variables declaration//GEN-END:variables
}
